package cfprobe

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// Cross-language vector generated by the Node controller's HMAC implementation.
const uninstallFixtureJSON = `{"type":"agent_uninstall","server_id":"11111111-1111-4111-8111-111111111111","command_id":"22222222-2222-4222-8222-222222222222","issued_at":1791446400000,"signature":"bdd664c77efd119301e23f4a65df6e36828cb9b6a9ab9c175352ca0d2ced3862"}`

func uninstallFixtureAgent(t *testing.T) *Agent {
	t.Helper()
	cfg := defaultConfig()
	cfg.ServerID = "11111111-1111-4111-8111-111111111111"
	cfg.Secret = "remote-uninstall-fixture-secret"
	ctx, cancel := context.WithCancel(t.Context())
	t.Cleanup(cancel)
	return &Agent{cfg: cfg, paths: Paths{ConfigDir: t.TempDir()}, ctx: ctx, cancel: cancel, log: newLogger(false)}
}

func TestRemoteUninstallRequiresExplicitSignedIntentForThisAgent(t *testing.T) {
	for _, body := range []string{
		`{"error":"Server not found","code":404}`,
		`{"type":"error","code":404,"error":"Server removed"}`,
		strings.Replace(uninstallFixtureJSON, "bdd664", "000000", 1),
		strings.Replace(uninstallFixtureJSON, "11111111-1111-4111-8111-111111111111", "33333333-3333-4333-8333-333333333333", 1),
		strings.Replace(uninstallFixtureJSON, "1791446400000", "1791446400001", 1),
		strings.Replace(uninstallFixtureJSON, "22222222-2222-4222-8222-222222222222", "../../foreign-service", 1),
		`{"type":"agent_uninstall"}`,
	} {
		a := uninstallFixtureAgent(t)
		if a.handleRemoteUninstall([]byte(body)) || a.ctx.Err() != nil {
			t.Fatalf("untrusted body stopped Agent: %s", body)
		}
		if _, err := os.Stat(remoteUninstallIntentFile(a.paths)); !os.IsNotExist(err) {
			t.Fatalf("untrusted body wrote uninstall intent: %v", err)
		}
	}
	a := uninstallFixtureAgent(t)
	if !a.handleRemoteUninstall([]byte(uninstallFixtureJSON)) || a.ctx.Err() == nil {
		t.Fatal("valid controller command did not stop collection/reporting")
	}
	command, pending := readRemoteUninstallIntent(a.paths, a.cfg)
	if !pending || command.CommandID != "22222222-2222-4222-8222-222222222222" {
		t.Fatalf("saved command cannot resume after restart: %+v", command)
	}
	info, err := os.Stat(remoteUninstallIntentFile(a.paths))
	if err != nil || info.Mode().Perm() != 0o600 {
		t.Fatalf("uninstall intent permissions: %v, %v", info, err)
	}
	if !a.handleRemoteUninstall([]byte(uninstallFixtureJSON)) {
		t.Fatal("duplicate command is not idempotent")
	}
}

func TestRemoteUninstallHTTPResponseStopsAgentButOrdinary404DoesNot(t *testing.T) {
	for _, body := range []string{`{"error":"Server not found","code":404}`, uninstallFixtureJSON} {
		t.Run(body[:20], func(t *testing.T) {
			a := uninstallFixtureAgent(t)
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusNotFound)
				fmt.Fprint(w, body)
			}))
			defer server.Close()
			a.cfg.ControllerURL = server.URL
			status, err := a.postReportBody(a.cfg, []byte(`{}`), 0, false)
			if err != nil || status != http.StatusNotFound {
				t.Fatalf("HTTP report failed: %d, %v", status, err)
			}
			if (a.ctx.Err() != nil) != (body == uninstallFixtureJSON) {
				t.Fatal("HTTP response handled with incorrect lifecycle behavior")
			}
		})
	}
}

func TestRemoteUninstallWebSocketCancelsTransportWithoutRetry(t *testing.T) {
	a := uninstallFixtureAgent(t)
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		conn, rw, err := w.(http.Hijacker).Hijack()
		if err != nil {
			t.Error(err)
			return
		}
		defer conn.Close()
		fmt.Fprintf(rw, "HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: %s\r\n\r\n", expectedWebSocketAccept(r.Header.Get("Sec-WebSocket-Key")))
		if err := rw.Flush(); err != nil {
			t.Error(err)
			return
		}
		ws := &webSocketConn{conn: conn, reader: rw.Reader}
		for _, body := range []string{`{"type":"hello","ts":1,"protocol":"update"}`, uninstallFixtureJSON} {
			if err := ws.writeFrame(wsOpcodeText, []byte(body), time.Second); err != nil {
				t.Error(err)
				return
			}
		}
	}))
	defer server.Close()
	a.cfg.ControllerURL = server.URL
	a.reporter = newReportTransport(a)
	ended := make(chan struct{})
	go func() { a.reporter.run(a.ctx); close(ended) }()
	select {
	case <-ended:
	case <-time.After(3 * time.Second):
		t.Fatal("transport kept retrying after valid uninstall command")
	}
	if a.ctx.Err() == nil {
		t.Fatal("WS command did not cancel Agent")
	}
	if _, pending := readRemoteUninstallIntent(a.paths, a.cfg); !pending {
		t.Fatal("WS command did not persist intent")
	}
}

func TestRemoteUninstallCannotCleanServicesForCustomForegroundConfig(t *testing.T) {
	installed := Paths{ServiceName: "jan-probe", ConfigFile: "/etc/config/cf-probe/config.conf", BinaryFile: "/usr/local/bin/jan-probe"}
	if !managedRemoteUninstall(installed, installed.BinaryFile, installed) {
		t.Fatal("normal managed installation rejected")
	}
	if managedRemoteUninstall(installed, filepath.Join(t.TempDir(), "jan-probe"), installed) {
		t.Fatal("uninstalled foreground binary can clean system services")
	}
	custom := installed
	custom.ConfigFile = filepath.Join(t.TempDir(), "config.conf")
	if managedRemoteUninstall(custom, installed.BinaryFile, installed) {
		t.Fatal("custom test configuration can clean system services")
	}
}

func TestRemoteUninstallSavedIntentIsBoundToCurrentConfig(t *testing.T) {
	a := uninstallFixtureAgent(t)
	var command agentUninstallCommand
	if err := json.Unmarshal([]byte(uninstallFixtureJSON), &command); err != nil {
		t.Fatal(err)
	}
	if err := saveRemoteUninstallIntent(a.paths, command); err != nil {
		t.Fatal(err)
	}
	cfg := a.cfg
	cfg.ServerID = "33333333-3333-4333-8333-333333333333"
	if _, pending := readRemoteUninstallIntent(a.paths, cfg); pending {
		t.Fatal("reconfigured Agent is subject to old deletion")
	}
	cfg = a.cfg
	cfg.Secret = "other-fixture-secret"
	if _, pending := readRemoteUninstallIntent(a.paths, cfg); pending {
		t.Fatal("invalid persisted signature accepted")
	}
}

func TestOfflineSampleBufferStaysWithinControllerReportLimit(t *testing.T) {
	a := uninstallFixtureAgent(t)
	a.cfg.ConnectionMode = connectionModeHTTP
	a.cfg.CollectInterval = 1
	a.lastPost = time.Now().Add(time.Hour)
	a.prevTime = time.Now()
	for i := 0; i < 450; i++ {
		a.lastSample = time.Time{}
		a.tick()
	}
	if len(a.samples) != agentSampleBufferLimit {
		t.Fatalf("failed reports accumulated %d samples", len(a.samples))
	}
	body, count, err := a.buildReportBody(Metrics{}, time.Now())
	if err != nil || count != 300 || len(body) >= 2*1024*1024 {
		t.Fatalf("offline Agent cannot reach controller lifecycle handler: samples=%d bytes=%d err=%v", count, len(body), err)
	}
}
